### ISSUE TITLE
max value and min value need to be consistent 

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/controller_configurator#13]
There is a function that needs to use the consistent name. Right now, all sensors has different strings. See here of min/max values

![image](https://github.com/user-attachments/assets/4359b416-7746-469b-aefc-56cada3ba9a5)

![image](https://github.com/user-attachments/assets/39cb7f2f-4f32-4fa6-8869-c481904926b2)

![image](https://github.com/user-attachments/assets/f0dcae68-c42f-408e-83ea-3c1d362a68b9)

![image](https://github.com/user-attachments/assets/2ecaea8b-24ba-4ac0-bda6-89b91731349c)

Let's set them to `max_value` and `min_value`

**Comment by Amir-Rasteg** [comment]
I am not seeing this at all in the main
